<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Wednesday 20th of November 2013 04:51:02 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://infocusphone.com/brid/hybridauth-2.1.2/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "547258865360762", "secret" => "01877919cecb0383c241b84e645697cb" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "Qb4LaEK3IqMbm54rzpsoEQ", "secret" => "Sh7YIFiCMydgxmc4rCpSmrzPN0fmMGjV7WCSnKydh7A" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
			"QQ" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "801445259", "secret" => "155c9ea4104b428fc78aea93ea71e9f0" ) 
			),

			"Sina" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "3630747112", "secret" => "a147cd7f794434d7c69e37f0b2d89966" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
